# Generated by Django 4.2.5 on 2023-11-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailedUserReport',
        ),
        migrations.DeleteModel(
            name='PoliceReport',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
