# Generated by Django 4.2.7 on 2023-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_delete_detaileduserreport_delete_policereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('question1', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('question3', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
                ('question4', models.CharField(max_length=255)),
                ('answer4', models.CharField(max_length=255)),
            ],
        ),
    ]
