# Generated by Django 4.2.7 on 2023-12-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_suggestions_userform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
